language: ruby
bundler_args: --without production
install:
   - "bundle install"
   - "npm install"
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key:
    secure: ENV['API_KEY']
  app: team-a-i-learn
  run:
    - restart
