development:
  adapter: postgresql
  host: 127.0.0.1
  database: i-learn-development
  username: test
  password: test
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  host: 127.0.0.1
  database: i-learn-test
  username: root
  password:

production:
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST']%>
  database: <%= ENV['DATABASE_NAME']%>
  username: <%= ENV['DATABASE_USERNAME']%>
  password: <%= ENV['DATABASE_PASSWORD']%>
  encoding: unicode
  pool: 5
  timeout: 5000
